
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BEUEjercicio
{

using System;
    using System.Collections.Generic;
    
public partial class tblLibro
{

    public int idlibro { get; set; }

    public string nombre { get; set; }

    public string autor { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

    public Nullable<int> reproducciones { get; set; }

    public Nullable<decimal> costo { get; set; }

}

}
